 # Copyright (c) 2023, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
datasets:
  wavcaps_mm_caption: # name of the dataset builder
    audio_processor:
        train:
          name: htsat_audio
          sampling_rate: 16000
          n_frames: 2
          frame_length: 512
        eval:
          name: htsat_audio
          sampling_rate: 16000
          n_frames: 2
          frame_length: 512
          
    text_processor:
        train:
          name: blip_caption
        eval:
          name: blip_caption

    data_type: [audio] 

    build_info:
      kwargs: 
        cached: False
        cached_dir: /fs/nexus-projects/brain_project/acl_sk_24/LAVIS/export/

      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: 
            - https://raw.githubusercontent.com/XinhaoMei/WavCaps/master/data/json_files/BBC_Sound_Effects/bbc_final.json
          storage: 
            - wavcaps/json_files/BBC_Sound_Effects/bbc_final.json
        # train:
        #   url: 
        #     - /export/share/datasets/audio/WavCaps/json_files/BBC_Sound_Effects/bbc_final.json
        #     - /export/share/datasets/audio/WavCaps/json_files/FreeSound/fsd_final.json
        #     - /export/share/datasets/audio/WavCaps/json_files/SoundBible/sb_final.json
        #     - /export/share/datasets/audio/WavCaps/json_files/AudioSet_SL/as_final.json
        #     - /export/share/datasets/audio/WavCaps/json_data.json
        #   storage: 
        #     - /export/share/datasets/audio/WavCaps/json_files/BBC_Sound_Effects/bbc_final.json
        #     - /export/share/datasets/audio/WavCaps/json_files/FreeSound/fsd_final.json
        #     - /export/share/datasets/audio/WavCaps/json_files/SoundBible/sb_final.json
        #     - /export/share/datasets/audio/WavCaps/json_files/AudioSet_SL/as_final.json
        #     - /export/share/datasets/audio/WavCaps/json_data.json
          
      # audio:
      #   storage: /export/share/datasets/audio/WavCaps/
  